site_name: My Docs
site_url: https://example.com
nav:
  - Home: index.md
  - About: about.md
  - Reference: reference/
theme: material
plugins:
  - gen-files:
      scripts:
        - scripts/generate_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            members_order: source
            group_by_category: false
            show_if_no_docstring: True
            signature_crossrefs: True
            modernize_annotations: True
